language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  
env:
  - DB=mysql
  - DB=mysqli
  - DB=pgsql
  - DB=sqlite
  - DB=pdo/mysql
  - DB=pdo/pgsql
  - DB=pdo/sqlite

sudo: false

services:
  - mysql

before_script:
  - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS ionize200;"
  - mysql -uroot -e "CREATE USER 'ionize200'@'localhost' IDENTIFIED BY 'ionize200';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON ionize200.* TO 'ionize200'@'localhost';"
  - mysql -uroot -e "FLUSH PRIVILEGES;"
  - mysql -uroot ionize200 < database.sql
  - composer install

script: php public/index.php

matrix:
  allow_failures:
    - php: hhvm
  exclude:
    - php: hhvm
      env: DB=pgsql
    - php: hhvm
      env: DB=pdo/pgsql
    - php: 7.0
      env: DB=mysql

branches:
  only:
    - develop
