language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  
env:
  - DB=mysql
  - DB=mysqli
  - DB=pgsql
  - DB=sqlite
  - DB=pdo/mysql
  - DB=pdo/pgsql
  - DB=pdo/sqlite

sudo: false

before_script: composer install

script: php public/index.php

matrix:
  allow_failures:
    - php: hhvm
  exclude:
    - php: hhvm
      env: DB=pgsql
    - php: hhvm
      env: DB=pdo/pgsql
    - php: 7.0
      env: DB=mysql

branches:
  only:
    - develop
